FROM node:19-alpine

WORKDIR /audiostick

COPY ["package.json", "tsconfig.json", ".env", "./"]

RUN apk update && apk add ffmpeg 

RUN npm install
RUN npm install typescript -g

COPY . .

RUN npm run build

CMD ["npm", "run", "start:prod"]
