FROM node:alpine

WORKDIR /audiostick

COPY ["package.json", "package-lock.json", "tsconfig.json", ".env", "./"]

RUN npm install\
    && npm install typescript -g

COPY . .

RUN tsc

CMD ["npm", "run", "start:prod"]
