FROM node:19-alpine

WORKDIR /audiostick

COPY ["package.json", "tsconfig.json", ".env", "./"]

RUN apk update && apk add ffmpeg 

RUN npm install\
    && npm install typescript -g

COPY . .

CMD ["npm", "run", "start:dev"]
