version: '3.9'
services:
  bot:
    container_name: bot
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.${SERVER}
    depends_on:
      - db
      # - api
    volumes:
    - .:/audiostick
    # - api:/var/lib/telegram-bot-api

  db:
    container_name: ${DB_HOST}
    restart: always
    image: postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

  # api:
  #   container_name: ${API_HOST}
  #   image: aiogram/telegram-bot-api:latest
  #   environment:
  #     - TELEGRAM_API_ID=${API_ID}
  #     - TELEGRAM_API_HASH=${API_HASH}
  #     - TELEGRAM_LOCAL=1
  #   volumes:
  #     - api:/var/lib/telegram-bot-api
  #   ports:
  #     - 8081:8081


volumes: 
  # api: {}
  data: {}
